# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home(主页)
    url: '#about'
    weight: 10
  - name: Experience(经历)
    url: '#posts'
    weight: 20
  - name: Blogs(博客)
    url: '#projects'
    weight: 30
  - name: Publications(论文)
    url: '#talks'
    weight: 40
  - name: Courses(课程)
    url: courses/
    weight: 50
  - name: Contact(联系)
    url: '#contact'
    weight: 60
